#!/usr/bin/env python3
"""Writes Resources/fr.lproj/Localizable.strings and lists UI strings in the code that have no translation."""
import pathlib, re, sys
root = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root / "scripts"))
from translations_fr import FR

def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

lines = ["/* Generated by scripts/make-strings.py from scripts/translations_fr.py */"]
lines += [f'"{escape(k)}" = "{escape(v)}";' for k, v in sorted(FR.items())]
(root / "Resources/fr.lproj/Localizable.strings").write_text("\n".join(lines) + "\n", encoding="utf-8")
# English needs entries only where a key differs from its English text.
EN = {"Done items": "Done"}
en = ["/* English is the development language: keys are the English strings, except below. */"]
en += [f'"{escape(k)}" = "{escape(v)}";' for k, v in sorted(EN.items())]
(root / "Resources/en.lproj/Localizable.strings").write_text("\n".join(en) + "\n", encoding="utf-8")

# Strings the UI shows: arguments of L(...) and SwiftUI literal initializers, with interpolations as format keys.
pattern = re.compile(r'(?:\bL\(|Text\(|Label\(|Button\(|Toggle\(|Picker\(|Section\(|LabeledContent\(|TextField\(|\.help\(|label: |title: |summary: |message: |help: |placeholder: |setupLabel: |"\s*,\s*$)\s*"((?:[^"\\]|\\.)*)"')
found = set()
for file in (root / "Sources").rglob("*.swift"):
    text = file.read_text()
    for match in pattern.finditer(text):
        key = match.group(1).replace("\\n", "\n").replace('\\"', '"')
        key = re.sub(r'\\\((?:\$0|count|layout\.done\.count)[^)]*\)', '%lld', key)
        key = re.sub(r'\\\([^)]*\)\)?', '%@', key)
        if re.search(r'[A-Za-z]{2,}', key) and not key.startswith(("http", "com.", "fr.")):
            found.add(key)
steps = re.findall(r'^\s*"([A-Z][^"]+\.)",?$', "\n".join(f.read_text() for f in (root / "Sources/RemoraPlugins").rglob("*.swift")), re.M)
found.update(steps)
missing = sorted(k for k in found if k not in FR and k not in EN)
print(f"{len(FR)} translations written; {len(missing)} UI strings without one:")
for key in missing:
    print("  -", key)
