#!/usr/bin/env python3
"""Writes Resources/fr.lproj/Localizable.strings and lists UI strings in the code that have no translation.
`--check` (CI) writes nothing and fails when a file is out of date or a UI string has no French."""

import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root / "scripts"))
from translations_fr import FR


def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


check = "--check" in sys.argv
stale = []


def write(path, lines):
    text = "\n".join(lines) + "\n"
    if not check:
        path.write_text(text, encoding="utf-8")
    elif not path.exists() or path.read_text(encoding="utf-8") != text:
        stale.append(str(path.relative_to(root)))


lines = ["/* Generated by scripts/make-strings.py from scripts/translations_fr.py */"]
lines += [f'"{escape(k)}" = "{escape(v)}";' for k, v in sorted(FR.items())]
write(root / "Resources/fr.lproj/Localizable.strings", lines)
# English needs entries only where a key differs from its English text.
EN = {"Done items": "Done"}
en = ["/* English is the development language: keys are the English strings, except below. */"]
en += [f'"{escape(k)}" = "{escape(v)}";' for k, v in sorted(EN.items())]
write(root / "Resources/en.lproj/Localizable.strings", en)
# Shown as written in every language: the app's name, and a form's example address.
UNTRANSLATED = {"Remora", "you@company.com"}


def interpolations(key):
    """`\\(…)` with nested parentheses → %lld for counts, else %@ (what SwiftUI and L() look up)."""
    out, i = "", 0
    while i < len(key):
        if key.startswith("\\(", i):
            depth, j = 1, i + 2
            while j < len(key) and depth:
                depth += {"(": 1, ")": -1}.get(key[j], 0)
                j += 1
            inner = key[i + 2 : j - 1]
            out += "%lld" if re.match(r"(\$0|count|layout\.done\.count)\b", inner) else "%@"
            i = j
        else:
            out += key[i]
            i += 1
    return out


# Strings the UI shows: arguments of L(...) and SwiftUI literal initializers, with interpolations as format keys.
pattern = re.compile(
    r'(?:\bL\(|Text\(|Label\(|Button\(|Toggle\(|Picker\(|Section\(|LabeledContent\(|TextField\(|\.help\(|label: |title: |summary: |message: |help: |placeholder: |setupLabel: |plural: |"\s*,\s*$)\s*"((?:[^"\\]|\\.)*)"'
)
found = set()
for file in (root / "Sources").rglob("*.swift"):
    text = file.read_text()
    for match in pattern.finditer(text):
        key = match.group(1).replace("\\n", "\n").replace('\\"', '"')
        key = interpolations(key)
        if re.search(r"[A-Za-z]{2,}", re.sub(r"%(?:lld|@|d)", "", key)) and not key.startswith(("http", "com.", "fr.")):
            found.add(key)
steps = re.findall(
    r'^\s*"([A-Z][^"]+\.)",?$',
    "\n".join(f.read_text() for f in (root / "Sources/RemoraPlugins").rglob("*.swift")),
    re.MULTILINE,
)
found.update(steps)
missing = sorted(k for k in found if k not in FR and k not in EN and k not in UNTRANSLATED)
if check:
    if stale:
        sys.exit(f"✗ out of date, run python3 scripts/make-strings.py: {', '.join(stale)}")
    if missing:
        sys.exit(
            "✗ UI strings without French (add them to scripts/translations_fr.py):\n"
            + "\n".join(f"  - {k}" for k in missing)
        )
    print(f"✓ Localizable.strings up to date; every UI string has French ({len(FR)} translations)")
else:
    print(f"{len(FR)} translations written; {len(missing)} UI strings without one:")
    for key in missing:
        print("  -", key)
