#!/usr/bin/env python3
"""Writes the emoji code table for both apps from the list below: Slack's and GitHub's names (gitmoji included) for
the emoji people and apps use most. `python3 scripts/make-emoji.py` after editing; `--check` fails when a table is
out of date. A code missing here stays as written (`:name:`), which is also what a workspace's own emoji do."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

EMOJI = {
    # Faces and people
    "smile": "😄",
    "smiley": "😃",
    "grinning": "😀",
    "grin": "😁",
    "laughing": "😆",
    "joy": "😂",
    "rofl": "🤣",
    "sweat_smile": "😅",
    "slightly_smiling_face": "🙂",
    "upside_down_face": "🙃",
    "wink": "😉",
    "blush": "😊",
    "innocent": "😇",
    "heart_eyes": "😍",
    "star-struck": "🤩",
    "kissing_heart": "😘",
    "yum": "😋",
    "stuck_out_tongue": "😛",
    "thinking_face": "🤔",
    "thinking": "🤔",
    "neutral_face": "😐",
    "expressionless": "😑",
    "no_mouth": "😶",
    "smirk": "😏",
    "unamused": "😒",
    "face_with_rolling_eyes": "🙄",
    "roll_eyes": "🙄",
    "grimacing": "😬",
    "relieved": "😌",
    "pensive": "😔",
    "sleepy": "😪",
    "sleeping": "😴",
    "mask": "😷",
    "face_with_head_bandage": "🤕",
    "nauseated_face": "🤢",
    "hot_face": "🥵",
    "cold_face": "🥶",
    "exploding_head": "🤯",
    "partying_face": "🥳",
    "sunglasses": "😎",
    "nerd_face": "🤓",
    "confused": "😕",
    "worried": "😟",
    "slightly_frowning_face": "🙁",
    "open_mouth": "😮",
    "astonished": "😲",
    "flushed": "😳",
    "pleading_face": "🥺",
    "cry": "😢",
    "sob": "😭",
    "scream": "😱",
    "fearful": "😨",
    "disappointed": "😞",
    "sweat": "😓",
    "tired_face": "😫",
    "yawning_face": "🥱",
    "triumph": "😤",
    "rage": "😡",
    "angry": "😠",
    "skull": "💀",
    "poop": "💩",
    "hankey": "💩",
    "clown_face": "🤡",
    "ghost": "👻",
    "alien": "👽",
    "robot_face": "🤖",
    "robot": "🤖",
    "see_no_evil": "🙈",
    "hugging_face": "🤗",
    "hugs": "🤗",
    "shushing_face": "🤫",
    "face_palm": "🤦",
    "facepalm": "🤦",
    "shrug": "🤷",
    "saluting_face": "🫡",
    "melting_face": "🫠",
    "eyes": "👀",
    "eye": "👁️",
    "brain": "🧠",
    "muscle": "💪",
    "wave": "👋",
    "raised_hand": "✋",
    "hand": "✋",
    "ok_hand": "👌",
    "v": "✌️",
    "crossed_fingers": "🤞",
    "point_right": "👉",
    "point_left": "👈",
    "point_up": "☝️",
    "point_down": "👇",
    "+1": "👍",
    "thumbsup": "👍",
    "-1": "👎",
    "thumbsdown": "👎",
    "clap": "👏",
    "raised_hands": "🙌",
    "open_hands": "👐",
    "pray": "🙏",
    "handshake": "🤝",
    "writing_hand": "✍️",
    "fist": "✊",
    "punch": "👊",
    "facepunch": "👊",
    "the_horns": "🤘",
    "call_me_hand": "🤙",
    "man-raising-hand": "🙋‍♂️",
    "woman-raising-hand": "🙋‍♀️",
    "raising_hand": "🙋",
    "bow": "🙇",
    "dancer": "💃",
    "runner": "🏃",
    "running": "🏃",
    "walking": "🚶",
    "busts_in_silhouette": "👥",
    "bust_in_silhouette": "👤",
    "baby": "👶",
    "ninja": "🥷",
    "detective": "🕵️",
    # Hearts and symbols
    "heart": "❤️",
    "orange_heart": "🧡",
    "yellow_heart": "💛",
    "green_heart": "💚",
    "blue_heart": "💙",
    "purple_heart": "💜",
    "black_heart": "🖤",
    "white_heart": "🤍",
    "broken_heart": "💔",
    "sparkling_heart": "💖",
    "100": "💯",
    "boom": "💥",
    "collision": "💥",
    "dizzy": "💫",
    "speech_balloon": "💬",
    "thought_balloon": "💭",
    "zzz": "💤",
    "white_check_mark": "✅",
    "heavy_check_mark": "✔️",
    "check": "✔️",
    "ballot_box_with_check": "☑️",
    "x": "❌",
    "negative_squared_cross_mark": "❎",
    "heavy_multiplication_x": "✖️",
    "warning": "⚠️",
    "no_entry": "⛔",
    "no_entry_sign": "🚫",
    "exclamation": "❗",
    "heavy_exclamation_mark": "❗",
    "grey_exclamation": "❕",
    "question": "❓",
    "grey_question": "❔",
    "bangbang": "‼️",
    "interrobang": "⁉️",
    "information_source": "ℹ️",
    "red_circle": "🔴",
    "large_orange_circle": "🟠",
    "large_yellow_circle": "🟡",
    "large_green_circle": "🟢",
    "large_blue_circle": "🔵",
    "large_purple_circle": "🟣",
    "black_circle": "⚫",
    "white_circle": "⚪",
    "red_square": "🟥",
    "large_green_square": "🟩",
    "arrow_right": "➡️",
    "arrow_left": "⬅️",
    "arrow_up": "⬆️",
    "arrow_down": "⬇️",
    "arrows_counterclockwise": "🔄",
    "repeat": "🔁",
    "recycle": "♻️",
    "heavy_plus_sign": "➕",
    "heavy_minus_sign": "➖",
    "new": "🆕",
    "free": "🆓",
    "up": "🆙",
    "cool": "🆒",
    "ok": "🆗",
    "sos": "🆘",
    "top": "🔝",
    "soon": "🔜",
    "end": "🔚",
    "back": "🔙",
    "on": "🔛",
    "copyright": "©️",
    "registered": "®️",
    "tm": "™️",
    "hash": "#️⃣",
    "star": "⭐",
    "star2": "🌟",
    "sparkles": "✨",
    "zap": "⚡",
    "fire": "🔥",
    "dart": "🎯",
    "trophy": "🏆",
    "medal": "🏅",
    "first_place_medal": "🥇",
    "crown": "👑",
    "gem": "💎",
    "moneybag": "💰",
    "dollar": "💵",
    "euro": "💶",
    "chart_with_upwards_trend": "📈",
    "chart_with_downwards_trend": "📉",
    "bar_chart": "📊",
    # Time and calendar (calendar and reminder apps)
    "calendar": "📆",
    "date": "📅",
    "spiral_calendar_pad": "🗓️",
    "spiral_calendar": "🗓️",
    "alarm_clock": "⏰",
    "clock1": "🕐",
    "clock3": "🕒",
    "clock9": "🕘",
    "clock12": "🕛",
    "stopwatch": "⏱️",
    "timer_clock": "⏲️",
    "hourglass": "⌛",
    "hourglass_flowing_sand": "⏳",
    "watch": "⌚",
    "bell": "🔔",
    "no_bell": "🔕",
    "loudspeaker": "📢",
    "mega": "📣",
    "speaker": "🔈",
    "mute": "🔇",
    "sound": "🔉",
    "loud_sound": "🔊",
    "tada": "🎉",
    "confetti_ball": "🎊",
    "balloon": "🎈",
    "gift": "🎁",
    "birthday": "🎂",
    "cake": "🍰",
    "christmas_tree": "🎄",
    "jack_o_lantern": "🎃",
    # Work and tools (gitmoji included)
    "memo": "📝",
    "pencil": "📝",
    "pencil2": "✏️",
    "pushpin": "📌",
    "round_pushpin": "📍",
    "paperclip": "📎",
    "link": "🔗",
    "lock": "🔒",
    "unlock": "🔓",
    "closed_lock_with_key": "🔐",
    "key": "🔑",
    "old_key": "🗝️",
    "mag": "🔍",
    "mag_right": "🔎",
    "bulb": "💡",
    "books": "📚",
    "book": "📖",
    "bookmark": "🔖",
    "page_facing_up": "📄",
    "clipboard": "📋",
    "file_folder": "📁",
    "open_file_folder": "📂",
    "card_index_dividers": "🗂️",
    "package": "📦",
    "inbox_tray": "📥",
    "outbox_tray": "📤",
    "email": "📧",
    "e-mail": "📧",
    "envelope": "✉️",
    "incoming_envelope": "📨",
    "mailbox": "📫",
    "phone": "☎️",
    "telephone_receiver": "📞",
    "iphone": "📱",
    "computer": "💻",
    "desktop_computer": "🖥️",
    "keyboard": "⌨️",
    "printer": "🖨️",
    "camera": "📷",
    "video_camera": "📹",
    "movie_camera": "🎥",
    "tv": "📺",
    "headphones": "🎧",
    "microphone": "🎤",
    "studio_microphone": "🎙️",
    "wrench": "🔧",
    "hammer": "🔨",
    "hammer_and_wrench": "🛠️",
    "gear": "⚙️",
    "nut_and_bolt": "🔩",
    "toolbox": "🧰",
    "construction": "🚧",
    "construction_worker": "👷",
    "rotating_light": "🚨",
    "triangular_flag_on_post": "🚩",
    "checkered_flag": "🏁",
    "rocket": "🚀",
    "airplane": "✈️",
    "car": "🚗",
    "bus": "🚌",
    "train": "🚆",
    "ship": "🚢",
    "bug": "🐛",
    "ambulance": "🚑",
    "lipstick": "💄",
    "art": "🎨",
    "fire_engine": "🚒",
    "white_flower": "💮",
    "green_apple": "🍏",
    "apple": "🍎",
    "lock_with_ink_pen": "🔏",
    "arrow_up_small": "🔼",
    "arrow_down_small": "🔽",
    "heavy_dollar_sign": "💲",
    "alembic": "⚗️",
    "label": "🏷️",
    "seedling": "🌱",
    "triangular_ruler": "📐",
    "straight_ruler": "📏",
    "children_crossing": "🚸",
    "building_construction": "🏗️",
    "vibration_mode": "📳",
    "egg": "🥚",
    "camera_flash": "📸",
    "wastebasket": "🗑️",
    "passport_control": "🛂",
    "adhesive_bandage": "🩹",
    "monocle_face": "🧐",
    "coffin": "⚰️",
    "test_tube": "🧪",
    "necktie": "👔",
    "stethoscope": "🩺",
    "bricks": "🧱",
    "technologist": "🧑‍💻",
    "money_with_wings": "💸",
    "thread": "🧵",
    "safety_vest": "🦺",
    "goal_net": "🥅",
    "twisted_rightwards_arrows": "🔀",
    "rewind": "⏪",
    "fast_forward": "⏩",
    "pause_button": "⏸️",
    "arrow_forward": "▶️",
    "stop_button": "⏹️",
    "beers": "🍻",
    "beer": "🍺",
    "wine_glass": "🍷",
    "coffee": "☕",
    "tea": "🍵",
    "pizza": "🍕",
    "hamburger": "🍔",
    "fries": "🍟",
    "taco": "🌮",
    "sushi": "🍣",
    "croissant": "🥐",
    "doughnut": "🍩",
    "cookie": "🍪",
    "popcorn": "🍿",
    "avocado": "🥑",
    "hot_pepper": "🌶️",
    "lemon": "🍋",
    "banana": "🍌",
    "strawberry": "🍓",
    "cherries": "🍒",
    "peach": "🍑",
    "watermelon": "🍉",
    # Nature and weather
    "sunny": "☀️",
    "partly_sunny": "⛅",
    "cloud": "☁️",
    "rain_cloud": "🌧️",
    "umbrella": "☂️",
    "snowflake": "❄️",
    "snowman": "⛄",
    "rainbow": "🌈",
    "ocean": "🌊",
    "earth_africa": "🌍",
    "earth_americas": "🌎",
    "earth_asia": "🌏",
    "globe_with_meridians": "🌐",
    "crescent_moon": "🌙",
    "full_moon": "🌕",
    "new_moon": "🌑",
    "tulip": "🌷",
    "rose": "🌹",
    "sunflower": "🌻",
    "cherry_blossom": "🌸",
    "herb": "🌿",
    "four_leaf_clover": "🍀",
    "maple_leaf": "🍁",
    "fallen_leaf": "🍂",
    "evergreen_tree": "🌲",
    "deciduous_tree": "🌳",
    "cactus": "🌵",
    "palm_tree": "🌴",
    "mushroom": "🍄",
    "dog": "🐶",
    "cat": "🐱",
    "mouse": "🐭",
    "rabbit": "🐰",
    "fox_face": "🦊",
    "bear": "🐻",
    "panda_face": "🐼",
    "koala": "🐨",
    "tiger": "🐯",
    "lion_face": "🦁",
    "cow": "🐮",
    "pig": "🐷",
    "frog": "🐸",
    "monkey_face": "🐵",
    "chicken": "🐔",
    "penguin": "🐧",
    "bird": "🐦",
    "eagle": "🦅",
    "owl": "🦉",
    "unicorn_face": "🦄",
    "bee": "🐝",
    "honeybee": "🐝",
    "butterfly": "🦋",
    "snail": "🐌",
    "turtle": "🐢",
    "snake": "🐍",
    "octopus": "🐙",
    "whale": "🐳",
    "dolphin": "🐬",
    "fish": "🐟",
    "tropical_fish": "🐠",
    "shark": "🦈",
    "crab": "🦀",
    "sloth": "🦥",
    "llama": "🦙",
    "t-rex": "🦖",
    "sauropod": "🦕",
    "dragon": "🐉",
    # Flags most used in French and English workspaces
    "flag-fr": "🇫🇷",
    "fr": "🇫🇷",
    "flag-gb": "🇬🇧",
    "gb": "🇬🇧",
    "uk": "🇬🇧",
    "flag-us": "🇺🇸",
    "us": "🇺🇸",
    "flag-eu": "🇪🇺",
    "flag-de": "🇩🇪",
    "de": "🇩🇪",
    "flag-es": "🇪🇸",
    "es": "🇪🇸",
    "flag-it": "🇮🇹",
    "it": "🇮🇹",
    "flag-be": "🇧🇪",
    "flag-ch": "🇨🇭",
    "flag-ca": "🇨🇦",
    "white_flag": "🏳️",
    "rainbow-flag": "🏳️‍🌈",
}


def swift() -> str:
    entries = ",\n".join(f'        "{name}": "{symbol}"' for name, symbol in sorted(EMOJI.items()))
    return f"""// Generated by scripts/make-emoji.py: edit the list there, not this file.

/// Emoji codes (`:tada:`) to emoji, for `Readable`.
enum Emoji {{
    static let table: [String: String] = [
{entries},
    ]
}}
"""


def rust() -> str:
    entries = "\n".join(f'    ("{name}", "{symbol}"),' for name, symbol in sorted(EMOJI.items()))
    return f"""// Generated by scripts/make-emoji.py: edit the list there, not this file.

//! Emoji codes (`:tada:`) to emoji, for `text::readable`.

pub const TABLE: &[(&str, &str)] = &[
{entries}
];
"""


TARGETS = {
    ROOT / "macos/Sources/RemoraCore/Application/Emoji.swift": swift,
    ROOT / "windows/crates/remora_core/src/emoji.rs": rust,
}

if __name__ == "__main__":
    check = "--check" in sys.argv
    stale = []
    for path, render in TARGETS.items():
        text = render()
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(text, encoding="utf-8")
            print(f"{path.relative_to(ROOT)}: {len(EMOJI)} codes")
    if stale:
        sys.exit(f"Out of date, run python3 scripts/make-emoji.py: {', '.join(map(str, stale))}")
